services:
  file-explorer:
    build: .
    ports:
      - "5099:5000"
    volumes:
      - ${HOST_DIR:-./data}:/data
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - FLASK_FILE_EXPLORER_BASE_DIR=/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s